

services:
  app:
    image: depresiku_be_img
    container_name: depresiku_be
    environment:
      APP_SERVICE: laravel.test
    ports:
      - "8000:8000"
    volumes:
      - ./src/laravel/:/var/www/html
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.1
    container_name: depresiku_db
    environment:
      MYSQL_ROOT_PASSWORD: pisanghoheng45
      MYSQL_DATABASE: db_depresiku
      MYSQL_USER: chojin
      MYSQL_PASSWORD: pisanghoheng45
    ports:
      - "3306:3306"
    volumes:
      - depresiku-db:/var/lib/mysql

volumes :
  depresiku-storage:
  depresiku-db:

